services:
  app:
    build: .
    container_name: inventory-manager-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        # Esta condición hace que el servicio 'app' espere a que 'db' esté listo.
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: bd_inventario
    restart: always
    ports:
      - "3317:3306"
    volumes:
      # Mapea un volumen local para asegurar la persistencia de los datos
      - "${DB_VOLUME_PATH}:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - app-network
    healthcheck: # <-- Agrega esto para verificar la salud del contenedor
      # El comando 'mysqladmin ping' verifica si el servidor está en línea.
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      timeout: 20s
      retries: 10

networks:
  app-network: